# SPDX-License-Identifier: (GPL-2.0+ OR MIT)
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_COMMON) += common/arch/registers/register_map.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_COMMON) += common/arch/registers/register_ops.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_COMMON) += common/arch/registers/register_ops_m8.o
