# SPDX-License-Identifier: GPL-2.0
ccflags-y += -I$(srctree)/drivers/usb/host/

$(MODULE_NAME)-$(CONFIG_AMLOGIC_CRG) += crg/crg.o


$(MODULE_NAME)-$(CONFIG_AMLOGIC_CRG) += crg/crg_drd.o

$(MODULE_NAME)-$(CONFIG_AMLOGIC_CRG) += crg/crg_udc.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_CRG) += crg/crg_usbphy.o

