#ifndef __WFEA_ERROR_H__
#define __WFEA_ERROR_H__
#include "../errcode_module.h"
enum
{
	WFEA_SUCCESS							=  SUCCESS,
	
	/*Common errors */
	WFEA_ERROR_GENERAL						= ERROR_W_FEA,
	WFEA_ERROR_ALREADY_INIT,
	WFEA_ERROR_NOT_INIT,
	WFEA_ERROR_ALREADY_START,
	WFEA_ERROR_NOT_START,
	WFEA_ERROR_RESOURCE_NOT_EXIST,
	WFEA_ERROR_RESOURCE_ALREADY_EXIST,
	WFEA_ERROR_LOAD_FILE,
	WFEA_ERROR_INVALID_PARA,
	WFEA_ERROR_INVALID_PARA_VALUE,
	WFEA_ERROR_NULL_HANDLE,
	WFEA_ERROR_INVALID_HANDLE,
	WFEA_ERROR_AUDIO_ENOUGH,
	WFEA_ERROR_AUDIO_NOT_END,
	WFEA_ERROR_INST_NULL,
	WFEA_ERROR_LOAD_LIBRARY,
	WFEA_ERROR_NO_ENOUGH_BUFFER,
	WFEA_ERROR_UNKNOW_TYPE,
	WFEA_ERROR_FAIL,
	WFEA_ERROR_EXCEPTION
};

#endif



