# SPDX-License-Identifier: GPL-2.0
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_ION) += common/ion_dev/ion/ion.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_ION) += common/ion_dev/ion/ion_heap.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_ION_SYSTEM_HEAP) += common/ion_dev/ion/ion_system_heap.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_ION_SYSTEM_HEAP) += common/ion_dev/ion/ion_system_contig_heap.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_ION_SYSTEM_HEAP) += common/ion_dev/ion/ion_page_pool.o
