#
# Makefile for the linux YAFFS filesystem routines.
#

obj-$(CONFIG_AMLOGIC_YAFFS_FS) += amlogic-fs-yaffs.o

amlogic-fs-yaffs-y := yaffs_ecc.o yaffs_vfs.o yaffs_guts.o yaffs_checkptrw.o
amlogic-fs-yaffs-y += yaffs_packedtags1.o yaffs_packedtags2.o yaffs_nand.o
amlogic-fs-yaffs-y += yaffs_tagscompat.o yaffs_tagsmarshall.o
amlogic-fs-yaffs-y += yaffs_endian.o
amlogic-fs-yaffs-y += yaffs_mtdif.o
amlogic-fs-yaffs-y += yaffs_nameval.o yaffs_attribs.o
amlogic-fs-yaffs-y += yaffs_allocator.o
amlogic-fs-yaffs-y += yaffs_yaffs1.o
amlogic-fs-yaffs-y += yaffs_yaffs2.o
amlogic-fs-yaffs-y += yaffs_bitmap.o
amlogic-fs-yaffs-y += yaffs_summary.o
amlogic-fs-yaffs-y += yaffs_verify.o
amlogic-fs-yaffs-y += yaffs_cache.o

