# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_VPU) += common/vpu/vpu.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_VPU) += common/vpu/vpu_reg.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_VPU) += common/vpu/vpu_power.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_VPU) += common/vpu/vpu_clk.o

