# SPDX-License-Identifier: GPL-2.0-only

$(MODULE_NAME)-$(CONFIG_AMLOGIC_MESON_IR) += ir/meson_ir_core.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_MESON_IR) += ir/meson_ir_main.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_MESON_IR) += ir/meson_ir_sysfs.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_MESON_IR) += ir/meson_ir_cdev.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_MESON_IR) += ir/meson_ir_raw.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_MESON_IR) += ir/meson_ir_regmap.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_MESON_IR) += ir/meson_ir_decoder_xmp.o