# SPDX-License-Identifier: (GPL-2.0+ OR MIT)
#Ascending by module name's ASCII

include $(COMMON_DRIVERS_DIR)/drivers/media/common/arch/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/common/canvas/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/common/ge2d/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/common/ion_dev/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/common/vpu/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/common/rdma/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/common/codec_mm/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/common/uvm/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/common/vfm/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/common/v4l_util/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/common/lut_dma/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/common/vpu_security/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/common/resource_mgr/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/common/dma-buf-heaps/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/common/sw_sync/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/common/vicp/Makefile