# SPDX-License-Identifier: GPL-2.0

#MODULE_NAME = amlogic_usb3_v2_phy
$(MODULE_NAME)-$(CONFIG_AMLOGIC_USBPHY) += usb3v2phy/phy-aml-new-usb3-v2.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_USBPHY) += usb3v2phy/phy-aml-new-usb3-com.o
