# SPDX-License-Identifier: (GPL-2.0+ OR MIT)
MEDIA_MODULE_NAME = aml_media
obj-$(CONFIG_AMLOGIC_MEDIA_MODULE) = $(MEDIA_MODULE_NAME).o
$(MEDIA_MODULE_NAME)-y = media_main.o
include $(COMMON_DRIVERS_DIR)/drivers/media/common/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/vout/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/video_sink/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/osd/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/vrr/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/deinterlace/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/di_multi/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/di_local/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/video_processor/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/enhancement/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/frame_sync/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/gdc/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/vin/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/cec/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/esm/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/atv_demod/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/dtv_demod/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/avsync/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/frc/Makefile
include $(COMMON_DRIVERS_DIR)/drivers/media/di_v4l/Makefile
