# SPDX-License-Identifier: (GPL-2.0+ OR MIT)
#
#Makefile for the Smart card driver.
#
#ccflags-y += -I$(srctree)/$(COMMON_DRIVERS_DIR)/include

$(MODULE_NAME)-$(CONFIG_AMLOGIC_SMARTCARD) += smartcard_sc2/smartcard.o
