# SPDX-License-Identifier: (GPL-2.0+ OR MIT)
#
# Makefile for the Canvas management driver.
#

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_CANVAS) += common/canvas/canvas.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_CANVAS) += common/canvas/canvas_mgr.o
