#pragma once

typedef enum
{
	PARAM_NONE							= 0,

	//IVW
	PARAM_W_IVW							= 1100,
	PARAM_W_IVW_VADON,	//0-VAD OFF; 1-VAD ON
	PARAM_W_IVW_AGCON,	//0-AGC OFF; 1-AGC ON

	//VAD
	PARAM_W_VAD							= 1200,
	PARAM_NENERGYTHRESHOLD,
	PARAM_NENDGAP,

	//FEA
	PARAM_W_FEA							= 1300,
	PARAM_W_FEA_DO_CMN,	//0-NO CMN; 1-DO CMN
	PARAM_W_FEA_MLP_JUMPFREAM_NUM,

	//MLP
	PARAM_W_MLP							= 1400,

	//DEC
	PARAM_W_DEC							= 1500,
	PARAM_W_DEC_NCMTHRESHOLD_KEYWORD1_ARC1,
	PARAM_W_DEC_NCMTHRESHOLD_KEYWORD2_ARC1,
	PARAM_W_DEC_NCMTHRESHOLD_KEYWORD3_ARC1,
	PARAM_W_DEC_NCMTHRESHOLD_KEYWORD4_ARC1,
	PARAM_W_DEC_NCMTHRESHOLD_KEYWORD5_ARC1,
	PARAM_W_DEC_NCMTHRESHOLD_KEYWORD6_ARC1,

	PARAM_W_DEC_NCMTHRESHOLD_LOW_KEYWORD1_ARC1,
	PARAM_W_DEC_NCMTHRESHOLD_LOW_KEYWORD2_ARC1,

	PARAM_W_DEC_NCMTHRESHOLD_PREWAKE_KEYWORD1_ARC1,
	PARAM_W_DEC_NCMTHRESHOLD_PREWAKE_KEYWORD2_ARC1,
	PARAM_W_DEC_NCMTHRESHOLD_PREWAKE_KEYWORD3_ARC1,
	PARAM_W_DEC_NCMTHRESHOLD_PREWAKE_KEYWORD4_ARC1,
	PARAM_W_DEC_NCMTHRESHOLD_PREWAKE_KEYWORD5_ARC1,
	PARAM_W_DEC_NCMTHRESHOLD_PREWAKE_KEYWORD6_ARC1,

	PARAM_W_DEC_NLMPENALTY,
	PARAM_W_DEC_WARMUP,	//0-NO WARMUP 1-DO WARMUP
	PARAM_W_DEC_MAX_STATE_LOOP,
	
	PARAM_W_DEC_USE_SIRANBI,

	//MAX PARAM IND
	PARAM_W_MAX							= 2000
}PARAM;

