# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_CVBS_OUTPUT) += vout/cvbs/cvbs_out.o vout/cvbs/cvbs_out_reg.o vout/cvbs/enc_clk_config.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_WSS) += vout/cvbs/wss.o

ccflags-y += -I$(COMMON_DRIVERS_DIR)/drivers/display/
