# SPDX-License-Identifier: (GPL-2.0+ OR MIT)
#
# Makefile for the amlogic dma buf drivers.
#

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_SECURE_DMABUF) += common/dma-buf-heaps/amlogic_secure_dmabuf.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HEAP_CMA) += common/dma-buf-heaps/amlogic_heap_cma.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_HEAP_CODEC_MM) += common/dma-buf-heaps/amlogic_heap_codec_mm.o