# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

asflags-y += -mfloat-abi=softfp -mfpu=neon
ccflags-y += -Idrivers/staging/android/ion

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_V4L_VIDEO3) += video_processor/v4lvideo/v4lvideo.o
