# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

KASAN_SANITIZE_dmc_monitor.o := n

$(MODULE_NAME)-$(CONFIG_AMLOGIC_DDR_TOOL)		+= ddr_tool/ddr_tool.o ddr_tool/ddr_port_desc.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_DDR_BANDWIDTH)		+= ddr_tool/ddr_bandwidth.o ddr_tool/ddr_priority.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_GXL) 	+= ddr_tool/ddr_band_op_gxl.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_GXL)	+= ddr_tool/ddr_band_op_gxl.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_GX)	+= ddr_tool/ddr_band_op_gx.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_G12)	+= ddr_tool/ddr_band_op_g12.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_A1)	+= ddr_tool/ddr_band_op_a1.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_T5)	+= ddr_tool/ddr_band_op_t5.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_T7)	+= ddr_tool/ddr_band_op_t7.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_S4)	+= ddr_tool/ddr_band_op_s4.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_S5)	+= ddr_tool/ddr_band_op_s5.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_C3)	+= ddr_tool/ddr_band_op_c3.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_T5M)	+= ddr_tool/ddr_band_op_t5m.o

$(MODULE_NAME)-$(CONFIG_AMLOGIC_DMC_MONITOR)		+= ddr_tool/dmc_monitor.o ddr_tool/dmc_port_sub.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_DMC_DEV_ACCESS)		+= ddr_tool/dmc_dev_access.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_DMC_MONITOR_G12)	+= ddr_tool/dmc_g12.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_DMC_MONITOR_TM2)	+= ddr_tool/dmc_tm2.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_DMC_MONITOR_GX)		+= ddr_tool/dmc_gx.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_DMC_MONITOR_C1)		+= ddr_tool/dmc_c1.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_DMC_MONITOR_T7)		+= ddr_tool/dmc_t7.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_DMC_MONITOR_S4)		+= ddr_tool/dmc_s4.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_DMC_MONITOR_S5)		+= ddr_tool/dmc_s5.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_DMC_MONITOR_C2)		+= ddr_tool/dmc_c2.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_DMC_MONITOR_C3)		+= ddr_tool/dmc_c3.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_DMC_MONITOR_T5M)	+= ddr_tool/dmc_t5m.o
