#ifndef __WMLP_ERROR_H__
#define __WMLP_ERROR_H__
#include "../errcode_module.h"

enum
{
	/* Generic Error defines */
	WMLP_SUCCESS							=  SUCCESS,


	/* Common errors */
	WMLP_ERROR_GENERAL						= ERROR_W_MLP,
	WMLP_ERROR_ALREADY_INIT,
	WMLP_ERROR_NOT_INIT,
	WMLP_ERROR_ALREADY_START,
	WMLP_ERROR_NOT_START,
	WMLP_ERROR_RESOURCE_NOT_EXIST,
	WMLP_ERROR_RESOURCE_ALREADY_EXIST,
	WMLP_ERROR_RESOURCE_NOT_RIGHT,
	WMLP_ERROR_LOAD_FILE,
	WMLP_ERROR_INVALID_PARA,
	WMLP_ERROR_INVALID_PARA_VALUE,
	WMLP_ERROR_NULL_HANDLE,
	WMLP_ERROR_INVALID_HANDLE,
	WMLP_ERROR_AUDIO_ENOUGH,
	WMLP_ERROR_AUDIO_NOT_END,
	WMLP_ERROR_INST_NULL,
	WMLP_ERROR_NO_ENOUGH_BUFFER,
	WMLP_ERROR_DONNT_SUPPORT,
	WMLP_ERROR_FAIL,
	WMLP_ERROR_EXCEPTION
};

#endif



