# SPDX-License-Identifier: (GPL-2.0+ OR MIT)
#
# Makefile for the amlogic ion device drivers.
#

#
# include ion_dev/ion for header files
#
include $(COMMON_DRIVERS_DIR)/drivers/media/common/ion_dev/ion/Makefile

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_ION_DEV) += common/ion_dev/dev_ion.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_ION_DEV) += common/ion_dev/ion_cma_heap.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_ION_DEV) += common/ion_dev/ion_codec_mm_heap.o
