# SPDX-License-Identifier: GPL-2.0

$(MODULE_NAME)-$(CONFIG_AMLOGIC_CRG) += crgdrdphy/phy-aml-crg-drd-usb2.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_CRG) += crgdrdphy/phy-aml-crg-drd-usb.o

$(MODULE_NAME)-$(CONFIG_AMLOGIC_CRG) += crgdrdphy/phy-aml-crg-drd-usb3.o

$(MODULE_NAME)-$(CONFIG_AMLOGIC_CRG) += crgdrdphy/phy-aml-crg-drd-otg-v2.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_CRG) += crgdrdphy/phy-aml-crg-drd-otg.o

$(MODULE_NAME)-$(CONFIG_AMLOGIC_CRG) += crgdrdphy/phy-aml-m31-usb2.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_CRG) += crgdrdphy/phy-aml-m31-usb3.o
