# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

ccflags-y += -I$(srctree)/drivers/gpio

$(MODULE_NAME)-$(CONFIG_AMLOGIC_WIFI) += wifi/wifi_dt.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_WIFI) += wifi/dhd_static_buf.o