# SPDX-License-Identifier: GPL-2.0

#MODULE_NAME = amlogic_usb2_phy
$(MODULE_NAME)-$(CONFIG_AMLOGIC_USB2PHY) += usb2phy/phy-aml-new-usb-v2.o
$(MODULE_NAME)-$(CONFIG_AMLOGIC_USB2PHY) += usb2phy/phy-aml-new-usb2-v2.o
