# SPDX-License-Identifier: (GPL-2.0+ OR MIT)
#
# Makefile for amdolby_vision
#

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_ENHANCEMENT_DOLBYVISION) += enhancement/amdolby_vision/amdv.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_ENHANCEMENT_DOLBYVISION) += enhancement/amdolby_vision/amdv_hw.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_ENHANCEMENT_DOLBYVISION) += enhancement/amdolby_vision/amdv_pq_config.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_ENHANCEMENT_DOLBYVISION) += enhancement/amdolby_vision/md_config.o
